### ISSUE TITLE
Support for primitive types in Array

### ISSUE THREAD

**Issue by andrewstam** [tang-amy/CS4500-group-public#2]
When trying to implement Array, the add() method requires an Object to be passed in. However, as per the assignment spec, Arrays need to be able to support storing ints, floats, bools, and Strings, and int, float, and bool do not have Object as their parent class. From the discussions on Piazza, it seems to be necessary to either create subclasses of Array for each of these specific types (such as IntArray, FloatArray, BoolArray, StrArray), or to create wrapper classes for these primitives so that we can pass them in as Objects. Would it be possible to change your API to support one of these two design decisions? Our preference would be wrapper classes for these primitive types, since then there's only one central Array implementation and it's fairly easy to make wrapper classes, but of course, the decision is up to you.

Here are the posts that we were looking at:
https://piazza.com/class/k51bluky59n2jr?cid=320
https://piazza.com/class/k51bluky59n2jr?cid=331

**Comment by tang-amy** [comment]
Hi, after re-reading the specs and the Piazza posts, we have also come to a similar conclusion. We feel that the separate classes for each type of array is better (i.e. IntArray, FloatArray, etc.). Additionally, we will be removing methods that we feel are unnecessary. I will update the API now, but I do not have time right now to update the tests. Please be patient about the tests and reach out as soon as possible if you have any more questions about the API.

**Comment by hakjoonlee** [comment]
Hello - thanks for updating the API to account for the different types. I did have a small concern with having the different Array classes inheriting from Object rather than Array, since that could lead to some code duplication, such as the size method. I wasn't sure if this was part of removing unnecessary methods, but I just wanted to bring it up.

**Comment by tang-amy** [comment]
It doesn't make sense to inherit from Array because Array is specifically an array of Objects.

**Comment by hakjoonlee** [comment]
Even if Array is an array of Objects, I still believe there should be some parent class from which all arrays inherit from. It just seems it'd be good design to have all arrays be connected by some parent as opposed to having them be separate classes. I don't think this is a big issue, but just a suggestion.

**Comment by bendavp** [comment]
The problem with having one class to inherit from is that you would not be able to use that Class like an Object. What would the constructor for that class look like? If each Array uses a different "under-the-hood" array then what would you do when trying to initialize that superclass? Currently in CwC there is no way of abstracting that superclass, so it may be confusing to the user.

Plus the code you are saving would only amount to several lines, really, because there aren't really that many functions that you can use from the superclass. Each Array class would need a different return type and/or parameter type(s) for most of the functions, and you can't override a function with a different return type.

**Comment by tang-amy** [comment]
The tests have been updated. I will add the remaining tests tomorrow.
